parameters:
    app.security.user.class.token_user_provider: Evolaze\Paiod\AppBundle\Security\User\TokenUserProvider
    app.provider.class.user: Evolaze\Paiod\AppBundle\Provider\UserProvider
    app.provider.class.message: Evolaze\Paiod\AppBundle\Provider\MessageProvider
    app.security.guard.class.token_authenticator: Evolaze\Paiod\AppBundle\Security\Guard\TokenGuardAuthenticator
    app.cache.adapter.class.pdo: Symfony\Component\Cache\Adapter\PdoAdapter
    app.cache.provider.class.keyvalue: Evolaze\Paiod\AppBundle\Cache\Provider\KeyvalueProvider
    app.controller.class.default: Evolaze\Paiod\AppBundle\Controller\DefaultController

services:
    app.controller.default:
        class: "%app.controller.class.default%"
        arguments:
            - "@app.provider.user"
            - "@app.provider.message"
    app.security.authenticator_token:
        class: "%app.security.guard.class.token_authenticator%"
    app.provider.message:
        class: "%app.provider.class.message%"
        arguments:
            - "@doctrine.orm.odm_entity_manager"
    app.provider.user:
        class: "%app.provider.class.user%"
        arguments:
            - "@doctrine.orm.orm_entity_manager"
            - "@app.cache.provider"
    app.provider.user_token:
        class: "%app.security.user.class.token_user_provider%"
        arguments:
            - "@doctrine.orm.orm_entity_manager"
    app.cache.adapter.pdo:
        class: "%app.cache.adapter.class.pdo%"
        arguments:
            - "pgsql:host=%keyvalue_host%;port=%keyvalue_port%;dbname=%keyvalue_name%"
            - ""
            - 0
            - { "db_username": "%keyvalue_user%", "db_password": "%keyvalue_password%" }

    app.cache.provider:
        class: "%app.cache.provider.class.keyvalue%"
        arguments:
            - "@app.cache.adapter.pdo"
