parent_box: debian/jessie64
box: sf-paiod
name: my-sf-paiod
memory: 1500
cpus: 2
ip: 192.168.2.2
provider_env:
    apt_key_dsn: hkp://p80.pool.sks-keyservers.net:80
    apt_key_recv: 58118E89F3A912897C070ADBF76221572C52609D
    apt_docker_source_path: /etc/apt/sources.list.d/docker.list
    apt_source_string: deb https://apt.dockerproject.org/repo debian-jessie main
    docker_engine_version: 17.03.0~ce-0~debian-jessie
    docker_compose_path: /usr/local/bin/docker-compose
    docker_compose_url: https://github.com/docker/compose/releases/download/1.9.0/run.sh
    locale: en_US.UTF-8
