version: "2"
services:
    back:
        build: ./php-fpm
        depends_on: ["keyvalue", "odm", "orm"]
        environment:
            TERM: rxvt
        hostname: back
        ports:
            - "9000:9000"
        restart: always
        volumes:
            - ./../symfony:/usr/share/symfony
    keyvalue:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD: keyvalue
            POSTGRES_USER: keyvalue
        hostname: keyvalue
        ports:
            - "5432:5432"
        restart: always
    orm:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD: orm
            POSTGRES_USER: orm
        hostname: orm
        ports:
            - "15432:5432"
        restart: always
    odm:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD: odm
            POSTGRES_USER: odm
        hostname: odm
        ports:
            - "25432:5432"
        restart: always
    front:
        build: ./nginx
        depends_on: ["back"]
        environment:
            TERM: rxvt
        hostname: front
        ports:
            - "80:80"
        volumes_from:
            - back
        restart: always
